---
- hosts: localhost
  connection: local

  roles:
    - prep
    - geerlingguy.homebrew
    - geerlingguy.dotfiles
    - geerlingguy.mas
    - hnakamur.osx-login-shell  # Set the shell to zsh
    # Set up applications
    - aerial
    - alfred3
    - iterm2
    - moom
    - ohmyzsh
    - ssh
    - sublime_text
    - unison
    - vim
    # Configure macOS
    - macos_config
    - dock
    - startup_login_items
