---
# Set the appropriate timezone
macos_timezone: America/Los_Angeles

# Set the computer and display sleep times
macos_display_sleep_time: 15

# Set various defaults which will update the relevant plist files
macos_os_defaults:
  # System Preferences & Globals
  - domain: Apple Global Domain
    values:
      # General / Appearance / Use dark menu bar and Dock
      AppleInterfaceStyle: Dark
      # Keyboard / Keyboard / Key Repeat
      KeyRepeat: 2
      # Keyboard / Keyboard / Delay Until Repeat
      InitialKeyRepeat: 25
      # Keyboard / Keyboard / Use all F1, F2, etc. keys as standard function keys
      com.apple.keyboard.fnState: true
      # Keyboard / Text / Correct spelling automatically
      NSAutomaticSpellingCorrectionEnabled: false
      # Keyboard / Text / Use smart quotes and dashes
      NSAutomaticQuoteSubstitutionEnabled: false
      NSAutomaticDashSubstitutionEnabled: false
      # Keyboard / Shortcuts / Full Keyboard Access / All controls
      AppleKeyboardUIMode: 3
      # Mouse / Point & Click / Tracking
      com.apple.mouse.scaling: 1.0
      # Keep natural scroll direction
      com.apple.swipescrolldirection: true

      # Enable subpixel font rendering on non-Apple LCDs
      AppleFontSmoothing: 2
      # Expand the save panel by default
      NSNavPanelExpandedStateForSaveMode: true
      NSNavPanelExpandedStateForSaveMode2: true
      # Disable the character accent menu when holding down a key
      ApplePressAndHoldEnabled: false

      PMPrintingExpandedStateForPrint: true
      PMPrintingExpandedStateForPrint2: true

  # Trackpad settings
  - domain: com.apple.AppleMultitouchTrackpad
    values:
      FirstClickThreshold: 1
      SecondClickThreshold: 1
      TrackpadCornerSecondaryClick: 2

  # System Preferences / Mouse
  - domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    values:
      # Point & Click / Secondary click
      MouseButtonMode: TwoButton

  # TODO(patsoffice) -- this does not appear to be working
  # System Preferences / App Store
  # - domain: /Library/Preferences/com.apple.SoftwareUpdate.plist
  #   values:
  #     # Disable 'Download newly available updates in the background'
  #     AutomaticDownload: false
  #     AutomaticallyInstallMacOSUpdates: false
  #   become: yes

  # Launch Services
  - domain: com.apple.LaunchServices
    values:
      # Disable the 'Are you sure you want to open this application?' dialog
      LSQuarantine: false

  # Login Window
  - domain: com.apple.loginwindow
    values:
      # Disable 'Reopen windows when logging back in' by default
      TALLogoutSavesState: false

  # Dock
  - domain: com.apple.dock
    values:
      # Start the screen saver in the bottom-left corner
      wvous-bl-corner: 5
      wvous-bl-modifier: 0
      # Put display to sleep in the bottom-right corner
      wvous-br-corner: 10
      wvous-br-modifier: 0
      # Set the icon size of dock items
      tilesize: 29
      # Enable magnification of icons
      magnification: false
      # Turn off launch animation
      launchanim: false
      # Make hidden applications translucent in the dock
      showhidden: true

  # Finder
  - domain: com.apple.finder
    values:
      # View / Show Path Bar
      ShowPathbar: true
      _FXShowPosixPathInTitle: true
      # View / Show Status Bar
      ShowStatusBar: true
      # Show hardrives and servers on the desktop
      ShowHardDrivesOnDesktop: true
      ShowExternalHardDrivesOnDesktop: true
      ShowMountedServersOnDesktop: true
      ShowRemovableMediaOnDesktop: true
      # Set the default Finder display mode to column view
      FXPreferredViewStyle: clmv
      MyDocsLibrarySavedViewStyle: clmv
      # Preferences / General / New Finder windows show / pjl
      NewWindowTarget: PfHm
      NewWindowTargetPath: file:///Users/pjl/
      # Preferences / Advanced / Keep folders on top when sorting by name (Sierra specific)
      _FXSortFoldersFirst: true
      # Preferences / Advanced / Disable 'Show warning before changing an extension'
      FXEnableExtensionChangeWarning: false
      # Disable animations
      DisableAllAnimations: true
      # Securely empty the trash
      EmptyTrashSecurely: true
      WarnOnEmptyTrash: false
      # Default view settings for list view
      StandardViewSettings: &view_settings
        ListViewSettings:
          columns:
            name:
              ascending: true
              index: 0
              visible: true
              width: 450
            size:
              ascending: false
              index: 1
              visible: true
              width: 100
            kind:
              ascending: true
              index: 2
              visible: true
              width: 150
            label:
              ascending: true
              index: 3
              visible: false
              width: 100
            version:
              ascending: true
              index: 4
              visible: false
              width: 75
            comments:
              ascending: true
              index: 5
              visible: false
              width: 300
            dateModified:
              ascending: false
              index: 6
              visible: true
              width: 200
            dateCreated:
              ascending: false
              index: 7
              visible: false
              width: 200
            dateLastOpened:
              ascending: false
              index: 8
              visible: false
              width: 200
        ExtendedListViewSettingsV2:
          calculateAllSizes: false
          columns:
          - ascending: true
            identifier: name
            visible: true
            width: 450
          - ascending: false
            identifier: size
            visible: true
            width: 100
          - ascending: true
            identifier: kind
            visible: true
            width: 150
          - ascending: true
            identifier: label
            visible: false
            width: 100
          - ascending: true
            identifier: version
            visible: false
            width: 75
          - ascending: true
            identifier: comments
            visible: false
            width: 300
          - ascending: false
            identifier: dateModified
            visible: true
            width: 200
          - ascending: false
            identifier: dateCreated
            visible: false
            width: 200
          - ascending: false
            identifier: dateLastOpened
            visible: false
            width: 200
      MyDocsLibrarySearchViewSettings: *view_settings
      # Search the current folder first
      FXDefaultSearchScope: SCcf
      # Open a new Finder window when a removable disk is accessed
      OpenWindowForNewRemovableDisk: true

  # Disk images
  - domain: com.apple.frameworks.diskimages
    values:
      auto-open-ro-root: true
      auto-open-rw-root: true
      skip-verify: true
      skip-verify-locked: true
      skip-verify-remote: true

  # Printing
  - domain: com.apple.print.PrintingPrefs
    values:
      '"Quit When Finished"': true

  # Screen saver
  - domain: com.apple.screensaver
    values:
      askForPassword: 1
      askForPasswordDelay: 0

  # Menu (Power)
  - domain: com.apple.menuextra.battery
    values:
      # Show Percentage
      ShowPercent: 'YES'
